"""usage ledger

Revision ID: 3298de782a7b
Revises: b6a5f798df51
Create Date: 2026-10-02 21:34:42.442732
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3298de782a7b'
down_revision: Union[str, None] = 'b6a5f798df51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('take_id', sa.UUID(), nullable=True),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['take_id'], ['takes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_session_id'), 'usage', ['session_id'], unique=False)
    op.create_index(op.f('ix_usage_take_id'), 'usage', ['take_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_take_id'), table_name='usage')
    op.drop_index(op.f('ix_usage_session_id'), table_name='usage')
    op.drop_table('usage')
    # ### end Alembic commands ###
