"""user role

Revision ID: b6a5f798df51
Revises: 208ef16fc396
Create Date: 2026-10-02 20:21:44.636027
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b6a5f798df51'
down_revision: Union[str, None] = '208ef16fc396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=16), server_default='learner', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
